In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/Projects/Fraud Detection Capstone Project/Datasets/Transaction Fraud Detection/cards_data.csv')
df_copy = df.copy()
df.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,07/2003,2004,No
3,42,825,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,01/2003,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,09/2008,2009,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6146 non-null   int64
 1   client_id              6146 non-null   int64
 2   card_brand             6146 non-null   object
 3   card_type              6146 non-null   object
 4   card_number            6146 non-null   int64
 5   expires                6146 non-null   object
 6   cvv                    6146 non-null   int64
 7   has_chip               6146 non-null   object
 8   num_cards_issued       6146 non-null   int64
 9   credit_limit           6146 non-null   object
 10  acct_open_date         6146 non-null   object
 11  year_pin_last_changed  6146 non-null   int64
 12  card_on_dark_web       6146 non-null   object
dtypes: int64(6), object(7)
memory usage: 624.3+ KB

In [4]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
np.set_printoptions(suppress=True)

In [5]:
df.describe()

,id,client_id,card_number,cvv,num_cards_issued,year_pin_last_changed
count,6146.00,6146.00,6146.00,6146.00,6146.00,6146.00
mean,3072.50,994.94,4820425803848956.00,506.22,1.50,2013.44
std,1774.34,578.61,1328582205754834.25,289.43,0.52,4.27
min,0.00,0.00,300105541992311.00,0.00,1.00,2002.00
25%,1536.25,492.25,4486365176018953.00,257.00,1.00,2010.00
50%,3072.50,992.00,5108957434464472.00,516.50,1.00,2013.00
75%,4608.75,1495.00,5585237469514469.00,756.00,2.00,2017.00
max,6145.00,1999.00,6997197066610978.00,999.00,3.00,2020.00

In [6]:
df.shape

(6146, 13)

In [7]:
df.isna().sum()

id                       0
client_id                0
card_brand               0
card_type                0
card_number              0
expires                  0
cvv                      0
has_chip                 0
num_cards_issued         0
credit_limit             0
acct_open_date           0
year_pin_last_changed    0
card_on_dark_web         0
dtype: int64

### card_brand

In [8]:
df['card_brand'].unique()

array(['Visa', 'Mastercard', 'Discover', 'Amex'], dtype=object)

In [9]:
df['card_brand'].value_counts()

card_brand
Mastercard    3209
Visa          2326
Amex           402
Discover       209
Name: count, dtype: int64

### card_type

In [10]:
df['card_type'].value_counts()

card_type
Debit              3511
Credit             2057
Debit (Prepaid)     578
Name: count, dtype: int64

### expires

In [16]:
df['expires'] = pd.to_datetime(df['expires'], format='%m/%Y').dt.to_period('M')
display(df['expires'].head())

0    2022-12
1    2020-12
2    2024-02
3    2024-08
4    2009-03
Name: expires, dtype: period[M]

In [17]:
df.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,2022-12,623,YES,2,$24295,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,2020-12,393,YES,2,$21968,04/2014,2014,No
2,3701,825,Visa,Debit,4582313478255491,2024-02,719,YES,2,$46414,07/2003,2004,No
3,42,825,Visa,Credit,4879494103069057,2024-08,693,NO,1,$12400,01/2003,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,2009-03,75,YES,1,$28,09/2008,2009,No

### has_chip

In [22]:
df['has_chip'] = df['has_chip'].map({'YES': True, 'NO': False})
df['has_chip'].value_counts()

has_chip
True     5500
False     646
Name: count, dtype: int64

### credit_limit

In [27]:
df['credit_limit'] = df['credit_limit'].str.replace("$", "").str.strip().astype(float)

### acc_open_date

In [35]:
df['acct_open_date'] = pd.to_datetime(df['acct_open_date'], format = '%m/%Y').dt.to_period('M')

In [36]:
df['year_pin_last_changed'] = pd.to_datetime(df['year_pin_last_changed'], format='%Y').dt.to_period('Y')
df['year_pin_last_changed'].head()

0    2008
1    2014
2    2004
3    2012
4    2009
Name: year_pin_last_changed, dtype: period[Y-DEC]

### card_on_dark_web

In [38]:
df['card_on_dark_web'].value_counts()

card_on_dark_web
No    6146
Name: count, dtype: int64

In [39]:
df.drop(columns='card_on_dark_web', inplace=True)

In [40]:
df.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed
0,4524,825,Visa,Debit,4344676511950444,2022-12,623,True,2,24295.00,2002-09,2008
1,2731,825,Visa,Debit,4956965974959986,2020-12,393,True,2,21968.00,2014-04,2014
2,3701,825,Visa,Debit,4582313478255491,2024-02,719,True,2,46414.00,2003-07,2004
3,42,825,Visa,Credit,4879494103069057,2024-08,693,False,1,12400.00,2003-01,2012
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,2009-03,75,True,1,28.00,2008-09,2009

In [41]:
df.to_csv('cleaned_card_data.csv', index=False)