In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/Projects/Fraud Detection Capstone Project/Datasets/Transaction Fraud Detection/users_data.csv')
df_copy = df.copy()
df.head()

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,$37891,$77254,$191349,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,$22681,$33483,$196,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,$163145,$249925,$202328,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,$53797,$109687,$183855,675,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 2000 non-null   int64
 1   current_age        2000 non-null   int64
 2   retirement_age     2000 non-null   int64
 3   birth_year         2000 non-null   int64
 4   birth_month        2000 non-null   int64
 5   gender             2000 non-null   object
 6   address            2000 non-null   object
 7   latitude           2000 non-null   float64
 8   longitude          2000 non-null   float64
 9   per_capita_income  2000 non-null   object
 10  yearly_income      2000 non-null   object
 11  total_debt         2000 non-null   object
 12  credit_score       2000 non-null   int64
 13  num_credit_cards   2000 non-null   int64
dtypes: float64(2), int64(7), object(5)
memory usage: 218.9+ KB

In [6]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
np.set_printoptions(suppress=True)

In [7]:
df.describe()

,id,current_age,retirement_age,birth_year,birth_month,latitude,longitude,credit_score,num_credit_cards
count,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00
mean,999.50,45.39,66.24,1973.80,6.44,37.39,-91.55,709.73,3.07
std,577.49,18.41,3.63,18.42,3.57,5.11,16.28,67.22,1.64
min,0.00,18.00,50.00,1918.00,1.00,20.88,-159.41,480.00,1.00
25%,499.75,30.00,65.00,1961.00,3.00,33.84,-97.39,681.00,2.00
50%,999.50,44.00,66.00,1975.00,7.00,38.25,-86.44,711.50,3.00
75%,1499.25,58.00,68.00,1989.00,10.00,41.20,-80.13,753.00,4.00
max,1999.00,101.00,79.00,2002.00,12.00,61.20,-68.67,850.00,9.00

In [8]:
df.isna().sum()

id                   0
current_age          0
retirement_age       0
birth_year           0
birth_month          0
gender               0
address              0
latitude             0
longitude            0
per_capita_income    0
yearly_income        0
total_debt           0
credit_score         0
num_credit_cards     0
dtype: int64

In [9]:
df.shape

(2000, 14)

In [10]:
df.head()

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,$37891,$77254,$191349,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,$22681,$33483,$196,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,$163145,$249925,$202328,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,$53797,$109687,$183855,675,1

In [15]:
cols = ['per_capita_income',	'yearly_income',	'total_debt']
for col in cols:
  df[col] = df[col].str.replace("$","").str.strip().astype(float)

In [16]:
df.head()

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,29278.00,59696.00,127613.00,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,37891.00,77254.00,191349.00,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,22681.00,33483.00,196.00,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,163145.00,249925.00,202328.00,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,53797.00,109687.00,183855.00,675,1

In [17]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [18]:
df.describe(include='all')

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
count,2000.00,2000.00,2000.00,2000.00,2000.00,2000,2000,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00
unique,NaN,NaN,NaN,NaN,NaN,2,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,Female,506 Washington Lane,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,1016,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,999.50,45.39,66.24,1973.80,6.44,NaN,NaN,37.39,-91.55,23141.93,45715.88,63709.69,709.73,3.07
std,577.49,18.41,3.63,18.42,3.57,NaN,NaN,5.11,16.28,11324.14,22992.62,52254.45,67.22,1.64
min,0.00,18.00,50.00,1918.00,1.00,NaN,NaN,20.88,-159.41,0.00,1.00,0.00,480.00,1.00
25%,499.75,30.00,65.00,1961.00,3.00,NaN,NaN,33.84,-97.39,16824.50,32818.50,23986.75,681.00,2.00
50%,999.50,44.00,66.00,1975.00,7.00,NaN,NaN,38.25,-86.44,20581.00,40744.50,58251.00,711.50,3.00
75%,1499.25,58.00,68.00,1989.00,10.00,NaN,NaN,41.20,-80.13,26286.00,52698.50,89070.50,753.00,4.00
max,1999.00,101.00,79.00,2002.00,12.00,NaN,NaN,61.20,-68.67,163145.00,307018.00,516263.00,850.00,9.00

In [21]:
df[df['address'].duplicated(keep=False)]

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
1411,960,29,66,1990,8,Male,506 Washington Lane,33.83,-117.85,26180.00,53376.00,60953.00,750,3
1535,1800,62,55,1958,2,Male,506 Washington Lane,37.48,-86.29,14038.00,9445.00,14856.00,641,2

In [23]:
df.to_csv('cleaned_user_data.csv', index=False)